# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/dcoffline/ublue
name: bazzite-fortress
# description will be included in the image's metadata
description: Eric's custom Bazzite image with GNOME and COSMIC

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-gnome
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into your image's root folder /

  - type: dnf
    repos:
      files:
        add:
          - https://repo.jotta.cloud/jotta-cli.repo
      copr:
        - ryanabx/cosmic-epoch # The COSMIC COPR!
    install:
      packages:
        - "@cosmic-desktop" # Now installed via DNF!
        - zsh
        - neovim
        - rclone
        - distrobox
        - htop
        - btop
        - bibata-cursor-themes
        - papirus-icon-theme
        - jotta-cli

  - type: systemd
    system:
      enabled:
        - cloudflared-update.timer # The timer will automatically trigger the .service!
        - cloudflared.service
        - rclone-mounts.service
    user:
      enabled:
        - jottad.service # This will now enable the official RPM service!
        - groq-dictate.service
        - monitor-control.service

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.github.tchx84.Flatseal
      - scope: user # Also add Flathub user repo, but no user packages
      
  - type: signing
