---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-fortress
# description will be included in the image's metadata
description: Eric's custom Bazzite image with GNOME and COSMIC

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-gnome
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: systemd
    user:
      enabled:
        - monitor-control.service
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      - usr: /usr

  - type: dnf
    repos:
    install:
      packages:
        - "@cosmic-desktop" # Now installed via DNF!
        - zsh
        - neovim
        - rclone
        - distrobox
        - htop
        - bibata-cursor-themes
        - papirus-icon-theme

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
          - dev.lizardbyte.app.Sunshine
          - com.github.tchx84.Flatseal
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
