# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/dcoffline/ublue
name: bazzite-fortress
# description will be included in the image's metadata
description: Eric's custom Bazzite image with GNOME and COSMIC

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-gnome
image-version: stable          # latest is also supported if you want new updates ASAP

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: /         # copies files/system/* into your image's root folder /

  - type: script
    snippets:
      - "mkdir -p /usr/local/bin" # Prepare for Cloudflared
  
  - type: dnf
    repos:
      copr:
      - ryanabx/cosmic-epoch    # The COSMIC COPR
    install:
      packages:
        - "@cosmic-desktop"     # The COSMIC desktop environment group
        - jotta-cli             # The official Jottacloud CLI client (RPM)
        - swayidle              # Idle management for sway (and COSMIC)
        - cloudflared           # Cloudflare Tunnel client
        
  - type: systemd
    system:
      enabled:
        - cloudflared.service
        - rclone-mounts.service
    user:
      enabled:
        - jottad.service          # This will now enable the official RPM service!
      
  - type: signing                 # KEEP COMMENTED OUT UNTIL YOU GENERATE YOUR KEYS!
